- Source/EventFlow/ReadStores/InMemory/IInMemoryReadModelStore.cs
- Source/EventFlow/ReadStores/InMemory/InMemoryReadModelStore.cs
Added some methods to the InMemoryReadModelStore:
- GetAll(): does what it says
- Find(Func<TReadModel, bool> predicate): Returns all readmodels that matches the provided predicate.
> Extended interface to the InMemoryReadModelStore

- Source/EventFlow.EventStores.MsSql/MssqlEventStore.cs
- Source/EventFlow.Test/Suites/EventStoreSuite.cs
- Source/EventFlow.Tests/EventFlow.Tests.csproj
- Source/EventFlow.Tests/IntegrationTests/EventStores/FilesEventStoreTests.cs
- Source/EventFlow/EventFlow.csproj
- Source/EventFlow/EventFlowOptions.cs
- Source/EventFlow/EventStores/EventStore.cs
- Source/EventFlow/EventStores/Files/FilesEventStore.cs
- Source/EventFlow/EventStores/Files/FilesEventStoreConfiguration.cs
- Source/EventFlow/EventStores/Files/IFilesEventStoreConfiguration.cs
- Source/EventFlow/EventStores/InMemory/InMemoryEventStore.cs
Create a basic files based event store. Fixes #11
> File based event store

- RELEASE_NOTES.md
- Source/EventFlow.EventStores.MsSql/MssqlEventStore.cs
- Source/EventFlow.MsSql.Tests/IntegrationTests/MsSqlIntegrationTestConfiguration.cs
- Source/EventFlow.MsSql/EventFlow.MsSql.csproj
- Source/EventFlow.MsSql/IMssqlConnection.cs
- Source/EventFlow.MsSql/MssqlConnection.cs
- Source/EventFlow.MsSql/RetryStrategies/ISqlErrorRetryStrategy.cs
- Source/EventFlow.MsSql/RetryStrategies/SqlErrorRetryStrategy.cs
- Source/EventFlow.ReadStores.MsSql/MssqlReadModelStore.cs
- Source/EventFlow.TestHelpers/Test.cs
- Source/EventFlow.Tests/EventFlow.Tests.csproj
- Source/EventFlow.Tests/UnitTests/CommandBusTests.cs
- Source/EventFlow.Tests/UnitTests/Core/LabelTests.cs
- Source/EventFlow.Tests/UnitTests/Core/TransientFaultHandlerTests.cs
- Source/EventFlow/CommandBus.cs
- Source/EventFlow/Configuration/EventFlowConfiguration.cs
- Source/EventFlow/Core/IRetryStrategy.cs
- Source/EventFlow/Core/ITransientFaultHandler.cs
- Source/EventFlow/Core/Label.cs
- Source/EventFlow/Core/RetryStrategies/IOptimisticConcurrencyRetryStrategy.cs
- Source/EventFlow/Core/RetryStrategies/OptimisticConcurrencyRetryStrategy.cs
- Source/EventFlow/Core/TransientFaultHandler.cs
- Source/EventFlow/EventFlow.csproj
- Source/EventFlow/EventFlowOptions.cs
> Transient fault handling

- Documentation/Aggregates.md
- Documentation/ValueObjects.md
- README.md
- RELEASE_NOTES.md
- Source/EventFlow.EventStores.EventStore.Tests/EventFlow.EventStores.EventStore.Tests.csproj
- Source/EventFlow.EventStores.EventStore.Tests/packages.config
- Source/EventFlow.EventStores.EventStore/EventFlow.EventStores.EventStore.csproj
- Source/EventFlow.EventStores.MsSql/EventFlow.EventStores.MsSql.csproj
- Source/EventFlow.EventStores.MsSql/packages.config
- Source/EventFlow.MsSql.Tests/EventFlow.MsSql.Tests.csproj
- Source/EventFlow.MsSql.Tests/packages.config
- Source/EventFlow.MsSql/EventFlow.MsSql.csproj
- Source/EventFlow.MsSql/packages.config
- Source/EventFlow.Owin/EventFlow.Owin.csproj
- Source/EventFlow.Owin/packages.config
- Source/EventFlow.ReadStores.MsSql/EventFlow.ReadStores.MsSql.csproj
- Source/EventFlow.ReadStores.MsSql/packages.config
- Source/EventFlow.TestHelpers/EventFlow.TestHelpers.csproj
- Source/EventFlow.TestHelpers/packages.config
- Source/EventFlow.Tests/EventFlow.Tests.csproj
- Source/EventFlow.Tests/UnitTests/ValueObjects/SingleValueObjectConverterTests.cs
- Source/EventFlow.Tests/packages.config
- Source/EventFlow/EventFlow.csproj
- Source/EventFlow/ValueObjects/ISingleValueObject.cs
- Source/EventFlow/ValueObjects/SingleValueObject.cs
- Source/EventFlow/ValueObjects/SingleValueObjectConverter.cs
Instead of producing JSON like this
```json
{
"Value": "awsome title"
}
```
Produce JSON that looks like this
```json
"awsome title"
```
> JSON converter that produces nicer results for single value objects

- Source/EventFlow/Configuration/Registrations/AutofacRegistration.cs
- Source/EventFlow/Configuration/Registrations/AutofacServiceRegistration.cs
> TypoFix - AutofacGeneticRegistration to AutofacGenericRegistration

- Source/EventFlow/Aggregates/IApply.cs
- Source/EventFlow/Aggregates/IEmit.cs
- Source/EventFlow/Subscribers/ISubscribeSynchronousTo.cs
- or maybe domainEvent
- one character parameter names can be confusing
> Can we use @event instead of e where possible?

- Source/EventFlow.Tests/UnitTests/Aggregates/MetadataTests.cs
- Source/EventFlow/Aggregates/AggregateRoot.cs
- Source/EventFlow/Aggregates/Metadata.cs
- Source/EventFlow/EventFlow.csproj
- Source/EventFlow/Exceptions/MetadataKeyNotFoundException.cs
- Source/EventFlow/Exceptions/MetadataParseException.cs
`Metadata` and `IMetadata` could use some improvements, making them easier to create and work with.
- Better exceptions if data is missing or fails to parse
- Easier creation and building
> Metadata improvements

- Source/EventFlow.TestHelpers/Test.cs
- Source/EventFlow.Tests/EventFlow.Tests.csproj
- Source/EventFlow.Tests/UnitTests/CommandBusTests.cs
- Source/EventFlow.Tests/UnitTests/Core/CircularBufferTests.cs
- Source/EventFlow/Aggregates/AggregateRoot.cs
- Source/EventFlow/Aggregates/IAggregateRoot.cs
- Source/EventFlow/CommandBus.cs
- Source/EventFlow/Core/CircularBuffer.cs
- Source/EventFlow/EventFlow.csproj
- Source/EventFlow/Exceptions/DuplicateOperationException.cs
http://blog.sapiensworks.com/post/2015/08/26/How-To-Ensure-Idempotency/
> Detect duplicate operations

- RELEASE_NOTES.md
- Source/EventFlow.MsSql.Tests/EventFlow.MsSql.Tests.csproj
- Source/EventFlow.Owin.Tests/EventFlow.Owin.Tests.csproj
- Source/EventFlow.RabbitMQ.Tests/EventFlow.RabbitMQ.Tests.csproj
see #129
for details see - https://connect.microsoft.com/VisualStudio/feedback/details/800245/vs2013rc-adds-to-vs2012-c-project-section-itemgroup
> Fix vs2015 testprojects

- RELEASE_NOTES.md
- Source/EventFlow.Tests/EventFlow.Tests.csproj
- Source/EventFlow.Tests/UnitTests/Provided/Specifications/AtLeastSpecificationTests.cs
- Source/EventFlow.Tests/UnitTests/Specifications/SpecificationTests.cs
- Source/EventFlow.Tests/UnitTests/Specifications/TestSpecifications.cs
- Source/EventFlow.Tests/UnitTests/Specifications/TestSpecificationsTests.cs
- Source/EventFlow/Aggregates/AggregateRoot.cs
- Source/EventFlow/EventFlow.csproj
- Source/EventFlow/Extensions/SpecificationExtensions.cs
- Source/EventFlow/Extensions/SpeficicationExtensions.cs
- Source/EventFlow/Provided/Specifications/AggregateIsNewSpecification.cs
- Source/EventFlow/Provided/Specifications/AllSpecification.cs
- Source/EventFlow/Provided/Specifications/AndSpeficication.cs
- Source/EventFlow/Provided/Specifications/AtLeastSpecification.cs
- Source/EventFlow/Provided/Specifications/NotSpecification.cs
- Source/EventFlow/Provided/Specifications/OrSpecification.cs
- Source/EventFlow/Provided/Specifications/SomeSpecification.cs
- Source/EventFlow/Specifications/ISpecification.cs
- Source/EventFlow/Specifications/Specification.cs
@JC008 What do you think? I wanted developers to be able to provide information regarding why a specification isn't satisfied.
Fixes #154
> Specifications

- RELEASE_NOTES.md
- Source/EventFlow.ReadStores.Elasticsearch/ElasticsearchReadModelStore.cs
- Source/EventFlow.ReadStores.MsSql/MssqlReadModelStore.cs
- Source/EventFlow.Tests/EventFlow.Tests.csproj
- Source/EventFlow.Tests/UnitTests/ReadStores/ReadModelFactoryTests.cs
- Source/EventFlow/EventFlow.csproj
- Source/EventFlow/EventFlowOptions.cs
- Source/EventFlow/ReadStores/IReadModelFactory.cs
- Source/EventFlow/ReadStores/InMemory/InMemoryReadStore.cs
- Source/EventFlow/ReadStores/MultipleAggregateReadStoreManager.cs
- Source/EventFlow/ReadStores/ReadModelEnvelope.cs
- Source/EventFlow/ReadStores/ReadModelFactory.cs
- Source/EventFlow/ReadStores/ReadStoreManager.cs
- Source/EventFlow/ReadStores/SingleAggregateReadStoreManager.cs
To allow developers to bootstrap their read models.
Fixes #171
> Read model factory

- Source/EventFlow.TestHelpers/Aggregates/Commands/ThingyImportCommand.cs
- Source/EventFlow.TestHelpers/EventFlow.TestHelpers.csproj
- Source/EventFlow.TestHelpers/Suites/TestSuiteForReadModelStore.cs
Related to the discussion in #165
> Fix: See if there's a problem regarding multiple emits and read models

- appveyor.yml
Integration tests are executed for branches created with the main repository and is required in order to do a release. Tests are executed against a Azure environment.
> Fix: Integration tests

- RELEASE_NOTES.md
- Source/EventFlow.EventStores.EventStore/EventStoreEventPersistence.cs
- Source/EventFlow.TestHelpers/Suites/TestSuiteForEventStore.cs
Based on PR #187 from @oliveiracdz
> Wrong expected version in EventStoreEvent

- Source/EventFlow.EventStores.EventStore.Tests/EventFlow.EventStores.EventStore.Tests.csproj
- Source/EventFlow.EventStores.EventStore.Tests/EventStoreRunner.cs
- Source/EventFlow.EventStores.EventStore.Tests/IntegrationTests/EventStoreEventStoreTests.cs
- Source/EventFlow.EventStores.EventStore.Tests/TcpHelper.cs
- appveyor.yml
EventStore (http://geteventstore.com/) inetagratgion tests sometimes fail due to ports already used.
> Fix EventStore integration test stability

- Source/EventFlow.Tests/IntegrationTests/SeparationTests.cs
- Source/EventFlow.Tests/VerifyTests.cs
- build.fsx
OpenCover should return error if NUnit returns error!
> Fail tests if NUnit returns error

- RELEASE_NOTES.md
- Source/EventFlow.Autofac/EventFlow.Autofac.nuspec
- Source/EventFlow.Elasticsearch/EventFlow.Elasticsearch.nuspec
- Source/EventFlow.EventStores.EventStore/EventFlow.EventStores.EventStore.nuspec
- Source/EventFlow.EventStores.MsSql/EventFlow.EventStores.MsSql.nuspec
- Source/EventFlow.Hangfire/EventFlow.Hangfire.nuspec
- Source/EventFlow.MsSql/EventFlow.MsSql.nuspec
- Source/EventFlow.Owin/EventFlow.Owin.nuspec
- Source/EventFlow.RabbitMQ/EventFlow.RabbitMQ.nuspec
- Source/EventFlow.ReadStores.MsSql/EventFlow.ReadStores.MsSql.nuspec
- Source/EventFlow.SQLite/EventFlow.SQLite.nuspec
- Source/EventFlow.Sql/EventFlow.Sql.nuspec
- Source/EventFlow/EventFlow.nuspec
Fixed nuspec files to point to the new project location.
> Nuspec fixes

- RELEASE_NOTES.md
- Source/EventFlow.Autofac.Tests/EventFlow.Autofac.Tests.csproj
- Source/EventFlow.Autofac/EventFlow.Autofac.csproj
- Source/EventFlow.Elasticsearch.Tests/EventFlow.Elasticsearch.Tests.csproj
- Source/EventFlow.Elasticsearch/EventFlow.Elasticsearch.csproj
- Source/EventFlow.EventStores.EventStore.Tests/EventFlow.EventStores.EventStore.Tests.csproj
- Source/EventFlow.EventStores.EventStore/EventFlow.EventStores.EventStore.csproj
- Source/EventFlow.Examples.Shipping.Tests/EventFlow.Examples.Shipping.Tests.csproj
- Source/EventFlow.Examples.Shipping/EventFlow.Examples.Shipping.csproj
- Source/EventFlow.Hangfire.Tests/EventFlow.Hangfire.Tests.csproj
- Source/EventFlow.Hangfire/EventFlow.Hangfire.csproj
- Source/EventFlow.MsSql.Tests/EventFlow.MsSql.Tests.csproj
- Source/EventFlow.MsSql/EventFlow.MsSql.csproj
- Source/EventFlow.Owin.Tests/EventFlow.Owin.Tests.csproj
- Source/EventFlow.Owin/EventFlow.Owin.csproj
- Source/EventFlow.RabbitMQ.Tests/EventFlow.RabbitMQ.Tests.csproj
- Source/EventFlow.RabbitMQ/EventFlow.RabbitMQ.csproj
- Source/EventFlow.SQLite.Tests/EventFlow.SQLite.Tests.csproj
- Source/EventFlow.SQLite/EventFlow.SQLite.csproj
- Source/EventFlow.Sql.Tests/EventFlow.Sql.Tests.csproj
- Source/EventFlow.Sql/EventFlow.Sql.csproj
- Source/EventFlow.TestHelpers/EventFlow.TestHelpers.csproj
- Source/EventFlow.Tests/EventFlow.Tests.csproj
- Source/EventFlow/EventFlow.csproj
- build.cake
- paket.dependencies
- paket.lock
Added NuGet package reference `DbUp` to `EventFlow.Sql`. The package was previously ILMerged, but that was removed by mistake in the update to the Cake build system. Instead of re-adding the ILMerge, the package is added as a NuGet reference.
> Added missing DbUp reference

- README.md
- Source/EventFlow.Tests/EventFlow.Tests.csproj
- Source/EventFlow.Tests/IntegrationTests/CompleteExampleTests.cs
- Source/EventFlow/Queries/ReadModelByIdQuery.cs
Update the README with a complete example
> Complete example

- RELEASE_NOTES.md
- Source/EventFlow.Tests/UnitTests/Aggregates/AggregateStoreTests.cs
- Source/EventFlow/Aggregates/AggregateStore.cs
Bug that this fixes was never released
> Fix: Aggreate store optimistic concurrency exception handling

- build.cake
This will make it considerably easier to find out what went wrong during a build.
> Upload tests results to AppVeyor

- RELEASE_NOTES.md
- Source/EventFlow.TestHelpers/Suites/TestSuiteForReadModelStore.cs
- Source/EventFlow/ReadStores/MultipleAggregateReadStoreManager.cs
- Source/EventFlow/ReadStores/SingleAggregateReadStoreManager.cs
Fixes a critical problem in the single aggregate read model store
#280
> Fix single aggregate read models

- Source/EventFlow.RabbitMQ/EventFlow.RabbitMQ.csproj
> Remove incorrect project reference

- Source/EventFlow/Aggregates/AggregateRoot.cs
- Source/EventFlow/Aggregates/AggregateState.cs
- Source/EventFlow/Extensions/TypeExtensions.cs
Sweep to remove CodeFactor issues
https://www.codefactor.io/repository/github/eventflow/eventflow/overview/develop
> Fix codefactor issues

- RELEASE_NOTES.md
- Source/EventFlow.Autofac/paket.template
- Source/EventFlow.Elasticsearch/paket.template
- Source/EventFlow.EventStores.EventStore/paket.template
- Source/EventFlow.Hangfire/paket.template
- Source/EventFlow.MsSql/paket.template
- Source/EventFlow.Owin/paket.template
- Source/EventFlow.RabbitMQ/paket.template
- Source/EventFlow.SQLite/paket.template
- Source/EventFlow.Sql/paket.template
- Source/EventFlow/paket.template
- build.cake
Make it easier to debug EventFlow by providing symbols and PDB files.
https://github.com/gittools/gitlink
> Symbols and PDB files

- RELEASE_NOTES.md
- build.cake
> Corrected repository path for gitlink

- Source/EventFlow.Sql/EventFlow.Sql.csproj
- Source/EventFlow.Sql/Integrations/DbUpUpgradeLog.cs
- Source/EventFlow.Sql/Migrations/SqlDatabaseMigrator.cs
- Source/EventFlow.Sql/ReadModels/ReadModelSqlGenerator.cs
dbup doesn't have .NET standard support yet
> EventFlow.Sql .NET Standard support

- RELEASE_NOTES.md
- Source/EventFlow.Tests/Exploration/RegisterSubscribersExplorationTests.cs
- Source/EventFlow/Extensions/EventFlowOptionsSubscriberExtensions.cs
- Source/EventFlow/Subscribers/DispatchToEventSubscribers.cs
> Fix subscriber registration

- RELEASE_NOTES.md
- Source/EventFlow.Tests/UnitTests/ReadStores/ReadModelPopulatorTests.cs
- Source/EventFlow/Extensions/ReadModelPopulatorExtensions.cs
- Source/EventFlow/ReadStores/IReadModelPopulator.cs
- Source/EventFlow/ReadStores/IReadModelStore.cs
- Source/EventFlow/ReadStores/IReadStoreManager.cs
- Source/EventFlow/ReadStores/ReadModelPopulator.cs
- Source/EventFlow/ReadStores/ReadStoreManager.cs
> Non generic purge and populate

- Source/EventFlow/EventFlow.csproj
> Build XML documentation

- Source/EventFlow.Elasticsearch.Tests/IntegrationTests/ElasticsearchReadModelStoreTests.cs
- Source/EventFlow.Elasticsearch/ReadStores/ElasticsearchReadModelStore.cs
- Source/EventFlow.MsSql.Tests/IntegrationTests/ReadStores/MsSqlReadModelStoreTests.cs
- Source/EventFlow.MsSql/ReadStores/MssqlReadModelStore.cs
- Source/EventFlow.SQLite.Tests/IntegrationTests/ReadStores/SQLiteReadStoreTests.cs
- Source/EventFlow.Sql/ReadModels/IReadModelSqlGenerator.cs
- Source/EventFlow.Sql/ReadModels/ReadModelSqlGenerator.cs
- Source/EventFlow.Sql/ReadModels/SqlReadModelStore.cs
- Source/EventFlow.TestHelpers/Suites/TestSuiteForReadModelStore.cs
- Source/EventFlow.Tests/IntegrationTests/ReadStores/InMemoryReadModelStoreTests.cs
- Source/EventFlow/ReadStores/IReadModelPopulator.cs
- Source/EventFlow/ReadStores/IReadModelStore.cs
- Source/EventFlow/ReadStores/InMemory/InMemoryReadStore.cs
- Source/EventFlow/ReadStores/ReadModelPopulator.cs
- Source/EventFlow/ReadStores/ReadModelStore.cs
- Easier deletion of individual read models
> Read model improvements

- Source/EventFlow.Owin.Tests/EventFlow.Owin.Tests.csproj
- Source/EventFlow.Owin.Tests/app.config
- build.cmd
- build.ps1
... and update Cake scripts
Fixes #398
> Fix Autofac dependency during build

- RELEASE_NOTES.md
- Source/EventFlow.Autofac.Tests/IntegrationTests/AutofacServiceRegistrationIntegrationTests.cs
- Source/EventFlow.TestHelpers/IntegrationTest.cs
- Source/EventFlow.TestHelpers/Suites/IntegrationTestSuiteForServiceRegistration.cs
- Source/EventFlow.Tests/IntegrationTests/CommandResultTests.cs
- Source/EventFlow.Tests/IntegrationTests/Core/IoC/EventFlowServiceRegistrationIntegrationTests.cs
- Source/EventFlow.Tests/IntegrationTests/Sagas/AggregateSagaTests.cs
- Source/EventFlow/Core/Caching/DictionaryMemoryCache.cs
- Source/EventFlow/Core/Caching/MemoryCache.cs
- Source/EventFlow/Core/Caching/NullCache.cs
- Source/EventFlow/Sagas/AggregateSagas/SagaAggregateStore.cs
> WIP: Autofac lifetime bugfix

- build.cake
> WIP: Fix Codecov integration

- RELEASE_NOTES.md
- Source/EventFlow.Tests/IntegrationTests/ReadStores/MultipleAggregateReadStoreManagerTests.cs
- Source/EventFlow/ReadStores/MultipleAggregateReadStoreManager.cs
> Fix: Event ordering for read models based on multiple aggregates

- RELEASE_NOTES.md
- Source/EventFlow.Tests/UnitTests/ValueObjects/SingleValueObjectConverterTests.cs
- Source/EventFlow.Tests/UnitTests/ValueObjects/SingleValueObjectTests.cs
- Source/EventFlow/ValueObjects/SingleValueObject.cs
> Enums as SingleValueObject<T>

- README.md
- RELEASE_NOTES.md
- Source/EventFlow.EventStores.EventStore/EventStoreEventPersistence.cs
- Source/EventFlow/Aggregates/IEventId.cs
- Source/EventFlow/Aggregates/IMetadata.cs
- Source/EventFlow/Aggregates/Metadata.cs
- Source/EventFlow/Core/MetadataContainer.cs
> EventStore cleanup

- Source/EventFlow/Aggregates/AggregateRoot.cs
> Validate arguments in AggregateRoot

- RELEASE_NOTES.md
- Source/EventFlow.EventStores.EventStore/EventFlow.EventStores.EventStore.csproj
Replaces #468 as agreed with @wgtmpeters 
Fixes #467
> Add .NET standard support to EventStore

- Source/EventFlow.RabbitMQ.Tests/Integration/RabbitMqTests.cs
Lets see if this could help until the root cause can be found
> RabbitMQ test stability

- README.md
Update link to EventStore home page
> Update link to EventStore home page in README.md

- RELEASE_NOTES.md
- Source/EventFlow.MsSql/EventStores/Scripts/0002 - Create eventdatamodel_list_type.sql
Keep schema consistent between scripts to resolve #578.
> add dbo schema

- RELEASE_NOTES.md
- Source/EventFlow.Tests/UnitTests/Extensions/BootstrapExtensionTests.cs
- Source/EventFlow/Extensions/EventFlowOptionsBootstrapExtensions.cs
Easily register bootstraps using this extension methods:
```csharp
EventFlowOptions.New.RunOnStartup<DatabaseInitializer>()
EventFlowOptions.New.RunOnStartup(() => Console.WriteLine("started!"))
```
> Added options.RunOnStartup<TBootstrap>()

- README.md
Ive added my example under the external example section.
> Added .net core example

- RELEASE_NOTES.md
- Source/EventFlow.MsSql.Tests/Extensions/MsSqlDatabaseExtensions.cs
- Source/EventFlow.MsSql.Tests/IntegrationTests/EventStores/MsSqlEventStoreTests.cs
- Source/EventFlow.MsSql.Tests/IntegrationTests/IdentityIndexFragmentationTests.cs
- Source/EventFlow.TestHelpers/MsSql/MsSqlConnectionString.cs
- Source/EventFlow/Core/GuidFactories.cs
- Source/EventFlow/Core/Identity.cs
> Fix: Index fragmentation using COMB GUIDs in MSSQL

- Source/EventFlow.MongoDB/ReadStores/MongoDbReadModelStore.cs
> Use FirstOrDefaultAsync instead of FirstAsync in Mongo ReadStore

- Source/EventFlow.EventStores.EventStore/EventFlow.EventStores.EventStore.csproj
Fixes #641. Not sure whether this brings implications for existing installations.
> Upgrade EventStore Client API

- Source/EventFlow.AspNetCore.Tests/EventFlow.AspNetCore.Tests.csproj
- Source/EventFlow.Autofac.Tests/EventFlow.Autofac.Tests.csproj
- Source/EventFlow.DependencyInjection.Tests/EventFlow.DependencyInjection.Tests.csproj
- Source/EventFlow.Elasticsearch.Tests/EventFlow.Elasticsearch.Tests.csproj
- Source/EventFlow.EntityFramework.Tests/EventFlow.EntityFramework.Tests.csproj
- Source/EventFlow.EventStores.EventStore.Tests/EventFlow.EventStores.EventStore.Tests.csproj
- Source/EventFlow.Examples.Shipping.Tests/EventFlow.Examples.Shipping.Tests.csproj
- Source/EventFlow.Hangfire.Tests/EventFlow.Hangfire.Tests.csproj
- Source/EventFlow.MongoDB.Tests/EventFlow.MongoDB.Tests.csproj
- Source/EventFlow.MsSql.Tests/EventFlow.MsSql.Tests.csproj
- Source/EventFlow.Owin.Tests/EventFlow.Owin.Tests.csproj
- Source/EventFlow.PostgreSql.Tests/EventFlow.PostgreSql.Tests.csproj
- Source/EventFlow.RabbitMQ.Tests/EventFlow.RabbitMQ.Tests.csproj
- Source/EventFlow.SQLite.Tests/EventFlow.SQLite.Tests.csproj
- Source/EventFlow.Sql.Tests/EventFlow.Sql.Tests.csproj
- Source/EventFlow.TestHelpers/EventFlow.TestHelpers.csproj
- Source/EventFlow.Tests/EventFlow.Tests.csproj
added NUnit test adapter to comply with .NET test adapter changes introduced in VS 15.8 (https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes-v15.8#testadapterextension); this should fix #640
> added NUnit test adapter

- RELEASE_NOTES.md
- Source/EventFlow.TestHelpers/Aggregates/ThingyAggregate.cs
- Source/EventFlow.Tests/UnitTests/Aggregates/AggregateRootTests.cs
- Source/EventFlow/Extensions/TypeExtensions.cs
> Allow explicit implementations of IEmit<>

- Source/EventFlow/Extensions/EventFlowOptionsSubscriberExtensions.cs
Fixes the registration of subscribers implementing the ISubscribeSynchonousToAll interface.
> Bugfix: Subscribe To All Domain Events

- RELEASE_NOTES.md
- Source/EventFlow.Tests/UnitTests/ValueObjects/SingleValueObjectTests.cs
- Source/EventFlow/ValueObjects/SingleValueObjectConverter.cs
> Fix: Deserializing "null" into nullable SingleValueObjects

- RELEASE_NOTES.md
- Source/EventFlow.MongoDB.Tests/IntegrationTests/ReadStores/MongoDbReadModelStoreTests.cs
- Source/EventFlow.MongoDB.Tests/IntegrationTests/ReadStores/Queries/MongoDbThingyGetWithLinqQuery.cs
- Source/EventFlow.MongoDB.Tests/IntegrationTests/ReadStores/QueryHandlers/MongoDbThingyGetWithLinqQueryHandler.cs
- Source/EventFlow.MongoDB/ReadStores/IMongoDbReadModelStore.cs
- Source/EventFlow.MongoDB/ReadStores/MongoDbReadModelStore.cs
give the option to query a mongodb read model store as an IQueryable
> mongoDB ReadModelStore as IQueryable

- Source/EventFlow.RabbitMQ/Integrations/RabbitMqPublisher.cs
to allow log instrumentation, e.g. applicationinsights dependency tracking
> move rabbitmq publish single message to own virtual method 

- Source/EventFlow.Tests/Exploration/EventUpgradeExplorationTest.cs
Explicitly showcase event upgrade.
> Add test for event upgrade

- Source/EventFlow.TestHelpers/MsSql/MsSqlHelpz.cs
- Source/EventFlow.Tests/IntegrationTests/ReadStores/MultipleAggregateReadStoreManagerTests.cs
- Source/EventFlow/EventStores/InMemory/InMemoryEventPersistence.cs
- appveyor.yml
- docker-compose.ci.yml
- up_integration-test-env.ps1
> Change to VS2019 image

- RELEASE_NOTES.md
- Source/EventFlow/Logs/Internals/ImportedLibLog.cs
Reduce memory allocation for log4net
> LibLog - Support structured logging in NLog 4.5 and newer

- RELEASE_NOTES.md
- Source/EventFlow/Aggregates/AggregateRoot.cs
- Source/EventFlow/EventStores/EventUpgradeManager.cs
- Source/EventFlow/Extensions/EventFlowOptionsCommandExtensions.cs
- Source/EventFlow/Extensions/EventFlowOptionsJobExtensions.cs
Fixes #714
Fixes #739
Fixes #690
> Small fixes

- Source/EventFlow.AspNetCore/EventFlow.AspNetCore.csproj
- Source/EventFlow.Autofac/EventFlow.Autofac.csproj
- Source/EventFlow.DependencyInjection/EventFlow.DependencyInjection.csproj
- Source/EventFlow.Elasticsearch/EventFlow.Elasticsearch.csproj
- Source/EventFlow.EntityFramework/EventFlow.EntityFramework.csproj
- Source/EventFlow.EventStores.EventStore/EventFlow.EventStores.EventStore.csproj
- Source/EventFlow.Hangfire/EventFlow.Hangfire.csproj
- Source/EventFlow.MongoDB/EventFlow.MongoDB.csproj
- Source/EventFlow.MsSql/EventFlow.MsSql.csproj
- Source/EventFlow.Owin/EventFlow.Owin.csproj
- Source/EventFlow.PostgreSql/EventFlow.PostgreSql.csproj
- Source/EventFlow.RabbitMQ/EventFlow.RabbitMQ.csproj
- Source/EventFlow.SQLite/EventFlow.SQLite.csproj
- Source/EventFlow.Sql/EventFlow.Sql.csproj
- Source/EventFlow.TestHelpers/EventFlow.TestHelpers.csproj
- Source/EventFlow/EventFlow.csproj
Release on master fails with 
```
C:\Users\appveyor\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19270-01\build\Microsoft.Build.Tasks.Git.targets(16,5): error MSB4018: The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly. [C:\projects\eventflow\Source\EventFlow\EventFlow.csproj]
C:\Users\appveyor\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19270-01\build\Microsoft.Build.Tasks.Git.targets(16,5): error MSB4018: System.TypeInitializationException: The type initializer for 'Microsoft.Build.Tasks.Git.TaskImplementation' threw an exception. [C:\projects\eventflow\Source\EventFlow\EventFlow.csproj]
C:\Users\appveyor\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19270-01\build\Microsoft.Build.Tasks.Git.targets(16,5): error MSB4018:  ---> …
```
> Fix master

- README.md
> Add Azure Functions and Event Grid example

- Source/EventFlow.Elasticsearch.Tests/IntegrationTests/ElasticsearchReadModelStoreTests.cs
- Source/EventFlow.EventStores.EventStore.Tests/IntegrationTests/EventStoreEventStoreTests.cs
- Source/EventFlow.PostgreSql.Tests/TestHelpers/PostgresSqlHelpz.cs
- Source/EventFlow.TestHelpers/MsSql/MsSqlHelpz.cs
- docker-compose.local.yml
- up_integration-test-local-env.ps1
Setup local environment via docker-compose to run integration tests locally: #757
> Allow to run integration tests locally

- Source/EventFlow.Tests/UnitTests/Subscribers/DispatchToEventSubscribersTests.cs
> Fixed test: SubscriberExceptionIsThrownIfConfigured
