eventflow/EventFlow

Documentation/Aggregates.md
RELEASE_NOTES.md
Source/EventFlow.TestHelpers/Aggregates/Test/TestAggregate.cs
Source/EventFlow.Tests/UnitTests/Aggregates/AggregateRootTests.cs
Source/EventFlow/Aggregates/AggregateRoot.cs

Allow developers to hide the aggregate event Apply methods by making them protected or private.
Fixes #76.

Allow aggregate event Apply methods to be private or protected

---

EventFlow.sln
RELEASE_NOTES.md
Source/EventFlow.Autofac.Tests/EventFlow.Autofac.Tests.csproj
Source/EventFlow.Autofac.Tests/Properties/AssemblyInfo.cs
Source/EventFlow.Autofac.Tests/UnitTests/Aggregates/AggregateFactoryTests.cs
Source/EventFlow.Autofac.Tests/app.config
Source/EventFlow.Autofac.Tests/packages.config
Source/EventFlow.Autofac/Aggregates/AggregateFactory.cs
Source/EventFlow.Autofac/EventFlow.Autofac.csproj
Source/EventFlow.Autofac/Extensions/EventFlowOptionsAutofacExtensions.cs
Source/EventFlow.Tests/EventFlow.Tests.csproj
Source/EventFlow/Configuration/Registrations/AutofacResolver.cs
Source/EventFlow/Configuration/Registrations/AutofacServiceRegistration.cs
Source/EventFlow/EventFlow.csproj
Source/EventFlow/Extensions/EventFlowOptionsAggregatesExtensions.cs

Added:
-  RegisterType() method to IServiceRegistration to simplify registering by type
- support for parameters in AutofacResolver.Resolve methods using overloads
- UseAutofacAggregateFactory() to EventFlowOptionsAutofacExtensions

Added an AutofacAggregateFactory to EventFlow.Autofac

---

RELEASE_NOTES.md
Source/EventFlow/Commands/Command.cs

- caused a break in project dependant on implicit ICommand<,> cast
- now matches Command<,,> with interface ICommand<,,>

ICommand<> defined on Command<,> in EventFlow.Commands

---

RELEASE_NOTES.md
Source/EventFlow/Exceptions/DomainError.cs

`DomainError.With(...)` no longer executes `string.format` if only one argument is parsed

Minor fix for DomainError.With

---

RELEASE_NOTES.md
Source/EventFlow.Tests/EventFlow.Tests.csproj
Source/EventFlow.Tests/UnitTests/Core/ReflectionHelperTests.cs
Source/EventFlow/Aggregates/AggregateRoot.cs
Source/EventFlow/Aggregates/AggregateState.cs
Source/EventFlow/CommandBus.cs
Source/EventFlow/Core/ReflectionHelper.cs
Source/EventFlow/EventStores/EventUpgradeManager.cs
Source/EventFlow/Queries/IQuery.cs
Source/EventFlow/Queries/IQueryHandler.cs
Source/EventFlow/Queries/QueryProcessor.cs
Source/EventFlow/ReadStores/ReadModelDomainEventApplier.cs
Source/EventFlow/Subscribers/DispatchToEventSubscribers.cs

It seems like this new code is about 36 times faster then the current using `MethodInfo` directly.
Here's the output
```
Timing Compiled
It took 0,112
Timing MethodInfo
It took 3,592
```
Here's the program
```csharp
public static class Program
{
public class Calculator
{
public int Add(int a, int b)
{
return a + b;
}
}
const int Count = 5000000;
public static int Main(string[] args)
{
Time(Compiled, "Compiled");
Time(MethodInfo, "MethodInfo");
return 0;
}
private static void Time(Func<Action> action, string label)
{
Console.WriteLine($"Timing {label}");
var timedaction = action();
var stopwatch = Stopwatch.StartNew();
timedaction();
stopwatch.Stop();
Console.WriteLine($"It took {stopwatch.Elapsed.TotalSeconds:0.000}");
}
private static Action Compiled()
{
var caller = …
```

Better performance for invocation of reflected methods

---

RELEASE_NOTES.md
Source/EventFlow.Tests/EventFlow.Tests.csproj
Source/EventFlow.Tests/UnitTests/Core/AsyncHelperTests.cs
Source/EventFlow/Core/AsyncHelper.cs

* Fixed: Deadlock in `AsyncHelper` if e.g. an exception caused no `async` tasks
to be scheduled. The `AsyncHelper` is used by EventFlow to expose non-`async`
methods to developers and provide the means to call `async` methods from
a synchronous context without causing a deadlock. There's no change to any of
the `async` methods.
The `AsyncHelper` is used in the following methods.
- `ICommandBus.Publish`
- `IEventStore.LoadEvents`
- `IEventStore.LoadAggregate`
- `IEventStore.LoadAllEvents`
- `IJobRunner.Execute`
- `IReadModelPopulator.Populate`
- `IReadModelPopulator.Purge`
- `IQueryProcessor.Process`

Fix deadlock problem in AsyncHelper

---

RELEASE_NOTES.md
Source/EventFlow.Hangfire.Tests/EventFlow.Hangfire.Tests.csproj
Source/EventFlow.Hangfire.Tests/Integration/HangfireJobFlow.cs
Source/EventFlow.Hangfire.Tests/paket.references
Source/EventFlow.Hangfire/EventFlow.Hangfire.csproj
Source/EventFlow.Hangfire/Integration/HangfireJobRunner.cs
Source/EventFlow.Hangfire/Integration/HangfireJobScheduler.cs
Source/EventFlow.Hangfire/Integration/IHangfireJobRunner.cs
Source/EventFlow.Hangfire/Integration/IJobDisplayNameBuilder.cs
Source/EventFlow.Hangfire/Integration/JobDisplayNameBuilder.cs
Source/EventFlow.Sql.Tests/EventFlow.Sql.Tests.csproj
Source/EventFlow.Sql/EventFlow.Sql.csproj
appveyor.yml

Developers can implement a custom `IJobDisplayNameBuilder` and control how a job display name is created.
@ylbillyli Would something like this work for #205?

Allow developers to control job display names in Hangfire

---

RELEASE_NOTES.md
appveyor.yml
build.cake
build.cmd
paket.lock

Currently the finished documentation is only available on the Read the Docs site. This PR will make sure the documentation is released along with the EventFlow NuGet packages.

Build and release documentation

---

Documentation/FAQ.rst

ICommandBus was misspelled as ICommadBus

---

Documentation/GettingStarted.rst

Aggrenate -> Aggregate
IDoamain -> IDomain
strait forward -> straightforward

Corrected spelling mistakes

---

RELEASE_NOTES.md
Source/EventFlow.Tests/UnitTests/Aggregates/AggregateRootTests.cs
Source/EventFlow/Aggregates/AggregateRoot.cs
Source/EventFlow/Aggregates/IAggregateRoot.cs

EventId was by mistake only based on the aggregate ID, making the ID the same for every single event emitted.
Fixes #325

Fix EventId generation

---

RELEASE_NOTES.md
Source/EventFlow.Autofac.Tests/UnitTests/AutofacServiceRegistrationTests.cs
Source/EventFlow.TestHelpers/Suites/TestSuiteForServiceRegistration.cs
Source/EventFlow/Extensions/ResolverExtensions.cs

When validating registrations, a lifetime scope should be used

---

RELEASE_NOTES.md
Source/EventFlow.Tests/UnitTests/Aggregates/AggregateStoreTests.cs
Source/EventFlow/Aggregates/AggregateStore.cs
Source/EventFlow/Subscribers/DomainEventPublisher.cs
Source/EventFlow/Subscribers/IDomainEventPublisher.cs

Makes it easier to propagate events from other bounded contexts through EventFlow as mentioned in #362.

Added new overload to DomainEventPublisher that that easier to use

---

RELEASE_NOTES.md
Source/EventFlow.Tests/IntegrationTests/Sagas/AlternativeSagaStoreTestClasses.cs
Source/EventFlow.Tests/IntegrationTests/Sagas/AlternativeSagaStoreTests.cs
Source/EventFlow.Tests/UnitTests/Sagas/DispatchToSagasTests.cs
Source/EventFlow/Sagas/DispatchToSagas.cs

I have a use case where a specific event might be part of a saga, but can also happen independently: Accounts can be created "on demand" during a payment process (`PaymentSaga`), but they might also be created beforehand.
Every time the `PaymentSagaLocator` encounters a standalone instance of the `AccountCreated` event, it won't find any payment metadata and cannot extract a payment id. So it returns a new id, leading to the saga's initialization - only to be discarded soon as this event doesn't start the saga. This seems counterintuitive.
I added the possibility to return `null` instead in order to short circuit the saga dispatcher process, as that was what I tried to do in the first place.

Allow LocateSagaAsync to return null

---

RELEASE_NOTES.md
Source/EventFlow/Extensions/StringExtensions.cs

StringExtensions.ToSha256() could not be used by concurrent threads because a static instance was involved. Fixed this issue by making it transient and disposing it.

Fixed #399: Made static Sha256 instance transient

---

RELEASE_NOTES.md
Source/EventFlow.Tests/UnitTests/EventStores/ConcurrentFilesEventPersistanceTests.cs
Source/EventFlow/EventStores/Files/FilesEventPersistence.cs
Source/EventFlow/Extensions/EventFlowOptionsEventStoresExtensions.cs

I did some research with regard to issue #357 (File store should be thread safe):
- Added some unit tests that simulate concurrent access. Could _not_ reproduce any issues when accessing a single instance from multiple threads.
- However, added locking for public methods that didn't have it already.
- Made the `FileEventsPersistence` registration a singleton instance.
Fixes #356
Fixes #357

FilesEventPersistence as singleton, added concurrency tests

---

RELEASE_NOTES.md
Source/EventFlow.Owin/Middlewares/CommandPublishMiddleware.cs
Source/EventFlow.Tests/IntegrationTests/UnicodeTests.cs
Source/EventFlow/Core/Identity.cs
Source/EventFlow/Core/Label.cs
Source/EventFlow/Core/VersionedTypes/VersionedTypeDefinitionService.cs

This is a proposal for issue #397.
Most regular expressions only check for english identifiers using `[A-Za-z0-9]`. While C# and .NET allow unicode characters in identifiers, this seems like an unnecessary restriction. This PR adds some tests with events, commands and identities with fancy names.
New expressions use [unicode general categories](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#SupportedUnicodeGeneralCategories), like that: `[\p{L}\p{Nd}]`
| Category | Description |
| ---------- | ------------ |
| L | All letter characters. Includes Lu, Ll, Lt, Lm, and Lo. |
| Lu | Letter, Lowercase |
| Lt | Letter, Titlecase |
| Lm | Letter, Modifier |
| Lo | Letter, Other |
| Nd | Number, Decimal Digit |
```antlr …
```

Added support for unicode type names

---

RELEASE_NOTES.md
Source/EventFlow.Tests/UnitTests/Core/IdentityTests.cs
Source/EventFlow/Core/Identity.cs

Previously, identity values were validated using `StartsWith` and checking on the name. You could create wrong values by accident, like this: `ThingyId.With("thingyINVALID-a41e...")`.
This PR updates the validation to take the hyphen into account. The regular expression can then be optimized to skip any non-hyphen character at the beginning, as this part already has been checked.

Identity prefix validation including dash

---

RELEASE_NOTES.md
Source/EventFlow.Tests/UnitTests/Core/VersionedTypes/VersionedTypeDefinitionServiceTestSuite.cs
Source/EventFlow.Tests/UnitTests/EventStores/EventDefinitionServiceTests.cs
Source/EventFlow/Core/VersionedTypes/IVersionedTypeDefinitionService.cs
Source/EventFlow/Core/VersionedTypes/VersionedTypeDefinitionService.cs
Source/EventFlow/EventStores/EventVersionAttribute.cs

Useful if by some mistake the same event made it to production using different names by mistake.

Remove single event version attribute limit

---

RELEASE_NOTES.md
Source/EventFlow.Tests/UnitTests/Core/ReflectionHelperTests.cs
Source/EventFlow/Core/ReflectionHelper.cs

http://docs.geteventflow.net/Aggregates.html#events states that Appy method _can_ be `private`
- recognise private methods
- update test

ReflectionHelper.CompileMethodInvocation

---

RELEASE_NOTES.md
Source/EventFlow.Tests/UnitTests/EventStores/ConcurrentInMemoryEventPersistanceTests.cs
Source/EventFlow/EventStores/Files/FilesEventPersistence.cs
Source/EventFlow/EventStores/InMemory/InMemoryEventPersistence.cs

This fixes #444 
As there is no ImmutableCollection in .NET Standard 1.6, I made an append-only `ImmutableEventCollection` that implements `IReadOnlyCollection` and can be safely returned from `LoadCommittedEventsAsync` without copying it all the time. 
First I tried making it a linked list of lists, so that committing would just append a node with the new events and enumerating would yield all events from the first node up to the current one, ignoring any next nodes, which would effectively make it immutable and enumeration-safe. But that made no difference performance-wise, so I went for the easier implementation that just wraps a list.
I looked into making `CommitEventsAsync` work without locks, but calculating the global sequence number just didn't work: The …

Fix: Concurrent access to InMemoryEventPersistence

---

RELEASE_NOTES.md
Source/EventFlow.MsSql/SnapshotStores/Scripts/0001 - Create EventFlowSnapshots.sql

Using MSSQL EventStore and SnapshotStore in the same database seems to cause conflicts:
```
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'PK_EventFlow' in the database.
Could not create constraint or index. See previous errors.
```
Renaming the snapshot PK to `PK_EventFlowSnapshots` seems to do the trick.

Change Primary Key name for MSSQL Snapshot Store

---

Source/EventFlow.AspNetCore.Tests/IntegrationTests/Site/SiteTests.cs
Source/EventFlow.AspNetCore/Middlewares/CommandPublishMiddleware.cs
Source/EventFlow.Owin.Tests/IntegrationTests/Site/SiteTests.cs
Source/EventFlow.Owin/Middlewares/CommandPublishMiddleware.cs

Adjusted the position of setting response status code to return proper status code, if catches exception. Also, added tests.
Please refer to the followings. (OWIN side, too. Fixed it)
[Set response status in ASP.NET core middleware - Stack Overflow](https://stackoverflow.com/questions/41966599/set-response-status-in-asp-net-core-middleware)

Fixed CommandPublishMiddleware as to return error, if exception occurs.

---

Source/EventFlow.Elasticsearch.Tests/IntegrationTests/ReadModels/ElasticsearchThingyReadModel.cs
Source/EventFlow.Elasticsearch/ReadStores/ElasticsearchReadModelStore.cs
Source/EventFlow.MsSql.Tests/IntegrationTests/ReadStores/ReadModels/MsSqlThingyReadModel.cs
Source/EventFlow.MsSql/ReadStores/MssqlReadModelStore.cs
Source/EventFlow.SQLite.Tests/IntegrationTests/ReadStores/ReadModels/SQliteThingyReadModel.cs
Source/EventFlow.Sql/ReadModels/SqlReadModelStore.cs
Source/EventFlow.TestHelpers/Aggregates/Commands/ThingyDeleteCommand.cs
Source/EventFlow.TestHelpers/Aggregates/Events/ThingyDeletedEvent.cs
Source/EventFlow.TestHelpers/Aggregates/ThingyAggregate.cs
Source/EventFlow.TestHelpers/Suites/TestSuiteForReadModelStore.cs
Source/EventFlow.Tests/IntegrationTests/ReadStores/ReadModels/InMemoryThingyReadModel.cs
Source/EventFlow.Tests/UnitTests/ReadStores/MultipleAggregateReadStoreManagerTests.cs
Source/EventFlow.Tests/UnitTests/ReadStores/ReadStoreManagerTestSuite.cs
Source/EventFlow/ReadStores/IReadModelContext.cs
Source/EventFlow/ReadStores/IReadModelStore.cs
Source/EventFlow/ReadStores/InMemory/InMemoryReadStore.cs
Source/EventFlow/ReadStores/ReadModelContext.cs
Source/EventFlow/ReadStores/ReadModelStore.cs
Source/EventFlow/ReadStores/ReadStoreManager.cs

Finally some use for the `IReadModelContext`:
``` csharp
public class InMemoryThingyReadModel : IReadModel,
IAmReadModelFor<ThingyAggregate, ThingyId, ThingyDeletedEvent>
{
public void Apply(IReadModelContext context, 
IDomainEvent<ThingyAggregate, ThingyId, ThingyDeletedEvent> domainEvent)
{
context.MarkForDeletion();
}
}

Mark read models for deletion

---

RELEASE_NOTES.md
Source/EventFlow.Elasticsearch.Tests/IntegrationTests/ReadModels/ElasticsearchThingyMessageReadModel.cs
Source/EventFlow.Elasticsearch/ReadStores/ElasticsearchReadModelStore.cs
Source/EventFlow.MsSql.Tests/IntegrationTests/ReadStores/ReadModels/MsSqlThingyMessageReadModel.cs
Source/EventFlow.MsSql/ReadStores/MssqlReadModelStore.cs
Source/EventFlow.SQLite.Tests/IntegrationTests/ReadStores/ReadModels/SQLiteThingyMessageReadModel.cs
Source/EventFlow.Sql/ReadModels/SqlReadModelStore.cs
Source/EventFlow.TestHelpers/Aggregates/Commands/ThingyAddMessageHistoryCommand.cs
Source/EventFlow.TestHelpers/Aggregates/Entities/ThingyMessageLocator.cs
Source/EventFlow.TestHelpers/Aggregates/Events/ThingyMessageHistoryAddedEvent.cs
Source/EventFlow.TestHelpers/Aggregates/ThingyAggregate.cs
Source/EventFlow.TestHelpers/Suites/TestSuiteForReadModelStore.cs
Source/EventFlow.Tests/IntegrationTests/ReadStores/ReadModels/InMemoryThingyMessageReadModel.cs
Source/EventFlow.Tests/UnitTests/ReadStores/MultipleAggregateReadStoreManagerTests.cs
Source/EventFlow.Tests/UnitTests/ReadStores/ReadStoreManagerTestSuite.cs
Source/EventFlow/ReadStores/IReadModelContext.cs
Source/EventFlow/ReadStores/IReadModelContextFactory.cs
Source/EventFlow/ReadStores/IReadModelStore.cs
Source/EventFlow/ReadStores/InMemory/InMemoryReadStore.cs
Source/EventFlow/ReadStores/ReadModelContext.cs
Source/EventFlow/ReadStores/ReadModelContextFactory.cs
Source/EventFlow/ReadStores/ReadModelStore.cs
Source/EventFlow/ReadStores/ReadStoreManager.cs

- Adds new properties to the `ReadModelContext`:
- `ReadModelId` contains the ID, in order to support one-to-many scenarios
- `IsNew` contains a value that indicates if this readmodel is being created
- Adds `ThingyMessageHistoryAddedEvent` as an example for one-to-many read models

ReadModelContext: Added ReadModelId and IsNew

---

RELEASE_NOTES.md
Source/EventFlow.TestHelpers/Aggregates/Commands/ThingyAddMessageHistoryCommand.cs
Source/EventFlow.TestHelpers/Aggregates/Commands/ThingyDeleteCommand.cs
Source/EventFlow.TestHelpers/Aggregates/Events/ThingyDeletedEvent.cs
Source/EventFlow.TestHelpers/Aggregates/Events/ThingyMessageHistoryAddedEvent.cs
Source/EventFlow.TestHelpers/Aggregates/Queries/DbContext.cs
Source/EventFlow.TestHelpers/Aggregates/Queries/DbContextQuery.cs
Source/EventFlow.TestHelpers/Aggregates/Queries/DbContextQueryHandler.cs
Source/EventFlow.TestHelpers/Aggregates/Queries/IDbContext.cs
Source/EventFlow.Tests/UnitTests/Aggregates/AggregateRootTests.cs
Source/EventFlow/Aggregates/AggregateRoot.cs
Source/EventFlow/Aggregates/IAggregateRoot.cs
Source/EventFlow/ReadStores/IReadModelContextFactory.cs
Source/EventFlow/ReadStores/ReadModelContextFactory.cs
Source/EventFlow/Snapshots/SnapshotAggregateRoot.cs

> - Aggregates must not assume that snapshots are created with increasing aggregate sequence numbers
>
> *Snapshot documentation*
I still managed to create a bug because of not having the actual Version value inside the `Apply` methods when snapshots were used.
This PR changes how events are applied in regard to aggregate sequence numbers:
- Possibly breaking: Removed `ApplyEvents(IEnumerable<IAggregateEvent>)`, which was only used by `AggregateRoot` itself and inlined it, in order to validate the current version for each applied event.
- Added `fromVersion` parameter: Sets the starting version after checking for initial state.
- Removed `domainEvents.Max(e => e.AggregateSequenceNumber)` because the Version should already be incremented

ApplyEvents: Better support for snapshots

---

RELEASE_NOTES.md
Source/EventFlow.SQLite.Tests/EventFlow.SQLite.Tests.csproj
Source/EventFlow.SQLite/EventFlow.SQLite.csproj

New version of System.Data.SQLite adds `netstandard2.0` target, which enables to use `EventFlow.SQLite` in `netcoreapp` projects.

Update System.Data.SQLite with netstandard2.0 target

---

appveyor.yml

Description
====
- Run RabbitMQ container before running build script by `before_build:` section
- An different approach from the #425 
Notes
====
- Increased about 4 minutes of build time by thick docker image (5GB) downloading time
- Solutions might be any of followings
- Use a linux image (< 100MB), if we could get [a premium subscription](https://help.appveyor.com/discussions/questions/2652-windows-server-2016#comment_45617459)
-  Make or find out more thin container image
-  Caching docker image by AppVeyor setting (I'm not sure the details)

Changes to use RabbitMQ docker container

---

RELEASE_NOTES.md
Source/EventFlow.Sql/ReadModels/ReadModelSqlGenerator.cs

Fixes #541 by introducing `ConcurrentDictionary<,'>` over `Dictionary<,>` in `ReadModelSqlGenerator`.

Concurrencyfix

---

Source/EventFlow.DependencyInjection.Tests/UnitTests/ServiceCollectionServiceRegistrationTests.cs
build.cake

- Fixed [this build warning](https://ci.appveyor.com/project/eventflow/eventflow/builds/19500559#L340)
Inherited test method `ValidateRegistrationsShouldDispose` is completely same as base class method. Removed it.
- Enabled `TreatWarningsAsErrors` build option
Build warnings would be build errors in CI.

Fixed build warning, enabled "build warning as error" in CI

---

RELEASE_NOTES.md
Source/EventFlow.AspNetCore.Tests/IntegrationTests/Site/Startup.cs
Source/EventFlow.AspNetCore/MetadataProviders/AddRequestHeadersMetadataProvider.cs
Source/EventFlow.AspNetCore/MetadataProviders/AddUserHostAddressMetadataProvider.cs
Source/EventFlow.AspNetCore/Middlewares/CommandPublishMiddleware.cs

Just fixing the namespace EventFlow.Aspnetcore to EventFlow.AspNetCore.

Rename Aspnetcore to AspNetCore namespace.

---

RELEASE_NOTES.md
Source/EventFlow.DependencyInjection/Registrations/ServiceProviderResolver.cs
Source/EventFlow.TestHelpers/Suites/TestSuiteForServiceRegistration.cs

In `ServiceProviderResolver` we used `ServiceProvider.GetService<T>` which returns `null` for unregistered services. In order to align the behavior with other resolver implementations (and user's expectations), this has been changed to use `GetRequiredService<T>` which throws an exception.
This fixes #574.

Fix: Use GetRequiredService in EventFlow.DependencyInjection

---

RELEASE_NOTES.md
Source/EventFlow.EntityFramework.Tests/InMemory/EfInMemoryEventStoreTests.cs
Source/EventFlow.EntityFramework.Tests/MsSql/EfMsSqlEventStoreTests.cs
Source/EventFlow.EntityFramework.Tests/PostgreSql/EfPostgreSqlEventStoreTests.cs
Source/EventFlow.EntityFramework.Tests/SQLite/EfSqliteEventStoreTests.cs
Source/EventFlow.EntityFramework/EventStores/EntityFrameworkEventPersistence.cs
Source/EventFlow.EventStores.EventStore.Tests/IntegrationTests/EventStoreEventStoreTests.cs
Source/EventFlow.MongoDB.Tests/IntegrationTests/EventStores/MongoDbEventStoreTests.cs
Source/EventFlow.MongoDB/EventStore/MongoDbEventPersistence.cs
Source/EventFlow.MsSql.Tests/IntegrationTests/EventStores/MsSqlEventStoreTests.cs
Source/EventFlow.MsSql/EventStores/MsSqlEventPersistence.cs
Source/EventFlow.PostgreSql.Tests/IntegrationTests/EventStores/PostgresSqlEventStoreTests.cs
Source/EventFlow.PostgreSql/EventStores/PostgresSqlEventPersistence.cs
Source/EventFlow.SQLite.Tests/IntegrationTests/EventStores/SQLiteEventStoreTests.cs
Source/EventFlow.SQLite/EventStores/SQLiteEventPersistence.cs
Source/EventFlow.TestHelpers/Suites/TestSuiteForEventStore.cs
Source/EventFlow.Tests/IntegrationTests/EventStores/FilesEventStoreTests.cs
Source/EventFlow.Tests/IntegrationTests/EventStores/InMemoryEventStoreTests.cs
Source/EventFlow/EventStores/Files/FilesEventPersistence.cs
Source/EventFlow/EventStores/InMemory/InMemoryEventPersistence.cs

This fixes issues with gaps in Global Sequence Numbers when replaying events. The problem occurs due to database internals like sequence caching, or even by using `IEventPersistence.DeleteEventsAsync`. I used `DeleteEventsAsync` to replicate the problem in our unit tests, but made it optional because I couldn't test all supported DBs.
I found another issue with `EventStoreEventPersistence` tests because the store cannot be reset between test runs. That leads to some tests getting red after repeated runs. I haven't found a way to reliably reset the store.

Fix LoadAllEventsAsync with gaps (#564)

---

RELEASE_NOTES.md
Source/EventFlow.TestHelpers/Aggregates/Decorators/SomeCommandHandlerDecorator.cs
Source/EventFlow.Tests/IntegrationTests/ResolverTests.cs
Source/EventFlow/Extensions/EventFlowOptionsCommandHandlerExtensions.cs
Source/EventFlow/Extensions/EventFlowOptionsEventUpgradersExtensions.cs
Source/EventFlow/Extensions/EventFlowOptionsMetadataProvidersExtensions.cs
Source/EventFlow/Extensions/EventFlowOptionsQueriesExtensions.cs
Source/EventFlow/Extensions/EventFlowOptionsSagasExtensions.cs
Source/EventFlow/Extensions/EventFlowOptionsSnapshotExtensions.cs
Source/EventFlow/Extensions/EventFlowOptionsSubscriberExtensions.cs
Source/EventFlow/Extensions/TypeExtensions.cs

Added checks in every Add* method for components that could potentially be decorated to filter out any types that have a constructor that takes a dependency on the same interface. This should catch any cases where a decorator gets incorrectly resolved, which leads to a stack overflow exception during resolution.
Added a failing to reproduce the issue.
This fixes #523

Fix: Stack overflow in ValidateRegistrations

---

RELEASE_NOTES.md
Source/EventFlow.Tests/UnitTests/ReadStores/AggregateReadStoreManagerTests.cs
Source/EventFlow.Tests/UnitTests/ReadStores/ReadModelDomainEventApplierTests.cs
Source/EventFlow/Core/ReflectionHelper.cs
Source/EventFlow/ReadStores/IAmAsyncReadModelFor.cs
Source/EventFlow/ReadStores/ReadModelDomainEventApplier.cs
Source/EventFlow/ReadStores/ReadStoreManager.cs

This adds support for async read model updates #577:
```csharp
public class AsyncPingReadModel : IReadModel,
IAmAsyncReadModelFor<ThingyAggregate, ThingyId, ThingyPingEvent>
{
public async Task ApplyAsync(IReadModelContext context, IDomainEvent<ThingyAggregate, ThingyId, ThingyPingEvent> domainEvent)
{
await Task.Delay(50);
PingEventsReceived = true;
}
...
```
You can mix and match asynchronous and synchronous updates, as long as you don't subscribe to the same event in both ways.

Async read model updates (IAmAsyncReadModelFor)

---

RELEASE_NOTES.md
Source/EventFlow.Tests/IntegrationTests/CancellationTests.cs
Source/EventFlow/Aggregates/AggregateStore.cs
Source/EventFlow/Configuration/Cancellation/CancellationBoundary.cs
Source/EventFlow/Configuration/Cancellation/ICancellationConfiguration.cs
Source/EventFlow/Configuration/IEventFlowConfiguration.cs
Source/EventFlow/EventFlowOptions.cs
Source/EventFlow/Subscribers/DomainEventPublisher.cs

Adds a configuration option to set the "point of no return" when using cancellation tokens. After this point in processing, cancellation tokens  are ignored:
`options.Configure(c => c.CancellationBoundary = CancellationBoundary.BeforeCommittingEvents)`
This fixes #65
I went a little overboard with tests, but couldn't find an easier way: Task completion sources control how far the process advances until the token is cancelled. A list of `IStep` instances controls the process and validation.

Added cancellation boundaries

---

Source/Common.props
Source/EventFlow.AspNetCore/EventFlow.AspNetCore.csproj
Source/EventFlow.Autofac/EventFlow.Autofac.csproj
Source/EventFlow.DependencyInjection/EventFlow.DependencyInjection.csproj
Source/EventFlow.Elasticsearch/EventFlow.Elasticsearch.csproj
Source/EventFlow.EntityFramework/EventFlow.EntityFramework.csproj
Source/EventFlow.EventStores.EventStore/EventFlow.EventStores.EventStore.csproj
Source/EventFlow.Hangfire/EventFlow.Hangfire.csproj
Source/EventFlow.MongoDB/EventFlow.MongoDB.csproj
Source/EventFlow.MsSql/EventFlow.MsSql.csproj
Source/EventFlow.Owin/EventFlow.Owin.csproj
Source/EventFlow.PostgreSql/EventFlow.PostgreSql.csproj
Source/EventFlow.RabbitMQ/EventFlow.RabbitMQ.csproj
Source/EventFlow.SQLite/EventFlow.SQLite.csproj
Source/EventFlow.Sql/EventFlow.Sql.csproj
Source/EventFlow.TestHelpers/EventFlow.TestHelpers.csproj
Source/EventFlow/EventFlow.csproj
build.cake
build.ps1

When you run `dotnet pack`, you'll have two packages:
- The standard package file `.nupkg`
- The symbol package file `.snupkg`
You have to upload both files on NuGet (the symbol file will be uploaded to the NuGet symbol server).
- Uncheck `Enable Just My Code`
- Check `Enable SourceLink`
- Add `https://symbols.nuget.org/download/symbols` to the list of symbol servers
The `.nuspec` file should contain a new entry:
```<repository type="git" url="https://github.com/eventflow/EventFlow" commit="xxx" />```
You can install the global SourceLink tool:
`dotnet tool install --global sourcelink`
and run
`sourcelink print-urls the-generated-pdb.pdb`
It should print all the raw source file URLs from GitHub

feat: SourceLink support

---

RELEASE_NOTES.md
Source/EventFlow.Tests/UnitTests/Sagas/AggregateSagas/AggregateSagaTests.cs
Source/EventFlow/Exceptions/CommandAggregateException.cs
Source/EventFlow/Exceptions/CommandException.cs
Source/EventFlow/Exceptions/SagaPublishException.cs
Source/EventFlow/Sagas/AggregateSagas/AggregateSaga.cs

I changed branch, issue #599 , original comment:
@rasmus requested changes on this pull request.
Thanks for the fix! Just a few comments
Add { } for if statements
Write a few tests to make sure it doesn't break at some point in the future
Update release notes
As this is a change in behaivor, we need to supply some method of disabling it. It might be a protected property named ThrowExceptionsOnFailedPublish which a default value of true
In Source/EventFlow/Sagas/AggregateSagas/AggregateSaga.cs:
>              }
+
+            if (0 < fails.Count)
+                if (1 == fails.Count)
+                    throw DomainError.With(fails[0].ToString());
I would really like to see the failed execution results added to the exception. That way developers get more information on what went wrong …

throw on failed saga command

---

RELEASE_NOTES.md
Source/EventFlow.MsSql/Integrations/TableParameter.cs
Source/EventFlow.TestHelpers/Suites/TestSuiteForEventStore.cs

Fixes #636
`TableParameter` class used `SqlDbType.Text` instead of `SqlDbType.NText`:
/// <summary>
/// <see cref="T:System.String" />. A variable-length stream of non-Unicode data with a maximum length of 2 31 -1 (or 2,147,483,647) characters.</summary>
Text = 18, // 0x00000012
/// <summary>
/// <see cref="T:System.String" />. A variable-length stream of Unicode data with a maximum length of 2 30 - 1 (or 1,073,741,823) characters.</summary>
NText = 11, // 0x0000000B
Now, this change could somehow break existing events, affect performance and prevent storing large events. Should we add a compatibility switch?

Fix: MsSqlEventPersistence with non-ANSI unicode characters

---

appveyor.yml

AppVeyor doesn't pick up `.snupkg` files according to https://github.com/appveyor/ci/issues/2753.
Documentation here: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg
EventFlow correctly builds the packages after #638

Publishing symbols

---

RELEASE_NOTES.md
Source/EventFlow.Tests/UnitTests/Configuration/Serialization/JsonOptionsTests.cs
Source/EventFlow.Tests/UnitTests/Extensions/JsonSerializerExtensionTests.cs
Source/EventFlow/Configuration/Serialization/ChainedJsonOptions.cs
Source/EventFlow/Configuration/Serialization/IJsonOptions.cs
Source/EventFlow/Configuration/Serialization/JsonOptions.cs
Source/EventFlow/EventFlowOptions.cs
Source/EventFlow/Extensions/EventFlowOptionsJsonConfigurationExtensions.cs
Source/EventFlow/Extensions/JsonOptionsExtensions.cs

As @frankebersoll pointed out in his PR #588, JSON serialization is currently configurable only by applying attributes directly to classes or by overriding global `JsonConvert.JsonSerializerSettings`. Unfortunately his PR was never merged, so I've reapplied some of this work and added some tests. This PR will allow configuring JSON serialization through `EventFlowOptions`:
```csharp
EventFlowOptions.New
.ConfigureJson(json => json
.AddSingleValueObjects()
.AddConverter<SomeConverter>()
);
```

JSON serialization config

---

Source/EventFlow.EventStores.EventStore/Extensions/EventFlowOptionsExtensions.cs

We use multiple applications on the same event store instance. We want to differentiate between these different applications and a way to do this is to make each connection name recognizable by an unique name.
I therefore suggest a small change to the extension method, so we can prepend the current  connectionname (with eventflow and version) with a custom string.

Make EventStore connection string configurable

---

Source/EventFlow.MongoDB/Extensions/MongoDbOptionsExtensions.cs
Source/EventFlow.MongoDB/ReadStores/IMongoDbReadModelStore.cs
Source/EventFlow.MongoDB/ReadStores/MongoDbReadModelStore.cs

Changes already done with other db providers in #393 applied also to MongoDb.

Remove empty constructor requirement on mongo readmodels

---

Source/EventFlow.AspNetCore/Configuration/EventFlowJsonOptionsMvcConfiguration.cs
Source/EventFlow.AspNetCore/EventFlow.AspNetCore.csproj
Source/EventFlow.AspNetCore/Extensions/AspNetCoreEventFlowOptions.cs
Source/EventFlow/EventFlow.csproj
appveyor.yml
docker-compose.ci.yml
up_integration-test-env.ps1

This let it works with a .net core 3 project and solves:
`System.TypeLoadException: 'Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'
`

.Net core 3 support

---

CONTRIBUTORS.md
README.md
RELEASE_NOTES.md
Source/EventFlow.PostgreSql.Tests/TestHelpers/PostgresSqlHelpz.cs
Source/EventFlow.Sql.Tests/UnitTests/ReadModels/ReadModelSqlGeneratorTests.cs
Source/EventFlow.Sql/Extensions/SqlStringExtensions.cs
Source/EventFlow.Sql/ReadModels/ReadModelSqlGenerator.cs
Source/EventFlow.Sql/ReadModels/ReadModelSqlGeneratorConfiguration.cs

That is the first step I would like to propose for the EventFlow, in the part of generation the SQL. What is does is quoting the column names while generating selects, updates or deletes. Those problems may be related mostly to SQL Server, to the problems while for instance you named your column:"UniqueIdentifier" which is data type in sql or you just have a column in your table that has the same name as system(SQL) tables or their columns.
The second step I would like to propose(if you approve the first one of course) is to propose a bit different way of generating those SQL with library like maybe Dapper but that is after I will make sure it will work for us.

Added quoting to generator of the SQL.

---

RELEASE_NOTES.md
Source/EventFlow.EntityFramework.Tests/EventFlow.EntityFramework.Tests.csproj
Source/EventFlow.EntityFramework/EventFlow.EntityFramework.csproj
Source/EventFlow/EventFlow.csproj

This adds multi-targeting for EventFlow.EntityFramework: For `netcoreapp3.1` targets we now use Entity Framework 3.1.1.
Fixes #718

Entity Framework on .NET Core 3.1

---

Source/EventFlow.Tests/IntegrationTests/ReadStores/MultipleAggregateReadStoreManagerTests.cs

```csharp
// Repopulating read models that span multiple aggregates should have their events
// applied in order using events time stamps
```
```
AggregateA v1 ==================================
{
"timestamp": "2020-07-05T10:20:01.6806857+00:00", (...)
}
AggregateA v2 ==================================
{
"timestamp": "2020-07-05T10:20:01.6963165+00:00", (...)
}
AggregateB v1 ==================================
{
"timestamp": "2020-07-05T10:20:01.6963165+00:00", (...)
}
AggregateB v2 ==================================
{
"timestamp": "2020-07-05T10:20:01.6963165+00:00", (...)
}
```
The timestamps of some events are identical, that's why sorting them mixes things up a bit. Even when I add 1ms delays between the calls, the timestamps still match as the clock resolution seems too low. I raised …

Fix MultipleAggregateReadStoreManagerTests

---

RELEASE_NOTES.md
Source/EventFlow.EntityFramework/EventStores/EntityFrameworkEventPersistence.cs

Entity Framework seems to make no guarantees about insertion order when using `AddRange`. This might lead to aggregate events with invalid GlobalSequenceNumber order.
I changed the code to call `SaveChanges` for every event.
This fixes #691

EntityFramework: SaveChanges per event

---

Source/EventFlow/Aggregates/AggregateRoot.cs

I think the exception message is wrong. It should state that it does NOT have an 'Apply' method.

Fix exception message for when it does not have an 'Apply' method that takes aggregate event
